name: 'irembo_voice_ai_dbt'
version: '1.0.0'
config-version: 2

profile: 'irembo_voice_ai'

model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  irembo_voice_ai_dbt:
    +materialized: view
    +schema: irembo_voice_ai

    bronze:
      +enabled: false

    silver:
      +materialized: view

    gold:
      +materialized: table